version: '3'

services:
  micronaut-stocks-service:
    container_name: micronaut-stocks-service
    build:
      dockerfile: stocks-service/Dockerfile
      context: ./
    environment:
      KAFKA_HOST: ${KAFKA_HOST}
    ports:
      - 10080:8080
  micronaut-events-listener:
    container_name: micronaut-events-listener
    build:
      dockerfile: stocks-events-listener/Dockerfile
      context: ./
    environment:
      KAFKA_HOST: ${KAFKA_HOST}
  micronaut-zookeeper:
    container_name: micronaut-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "10181:2181"
  micronaut-kafka:
    container_name: micronaut-kafka
    image: wurstmeister/kafka
    ports:
      - "10092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}
      KAFKA_CREATE_TOPICS: "micronaut-stocks:1:1"
      KAFKA_ZOOKEEPER_CONNECT: micronaut-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock