micronaut:
  application:
    name: stocks
  server:
    port: 8080
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/public/**"
        paths: "classpath:public"
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  io:
    watch:
      paths: src/main
      restart: true