micronaut:
  application:
    name: stocks-service
  server:
    port: 8080
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/public/**"
        paths: "classpath:public"
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
kafka:
  bootstrap:
    servers: ${KAFKA_HOST:localhost}:10092